---
- name: Get OCP Release Version
  shell: curl -s {{ hypershift.asc.url_for_ocp_release_file }}  | awk '/machine-os / { print $2 }'
  register: ocp_release_version

- name: Create Config map mirror-config ( For updating AgentServiceConfig with the brew mirror information )
  template: 
    src: mirror-config.yml.j2
    dest: /root/ansible_workdir/mirror-config.yaml

- name: Deploy Config map - mirror config
  shell: oc apply -f /root/ansible_workdir/mirror-config.yaml

- name: Create agenterviceconfig.yaml
  template: 
    src: agent_service_config.yaml.j2
    dest: /root/ansible_workdir/agentserviceconfig.yaml

- name: Deploy AgentServiceConfig
  command: oc apply -f /root/ansible_workdir/agentserviceconfig.yaml

- name: Wait for Agent Service Deployment to be Succeeded
  shell: oc get AgentServiceConfig agent -o json | jq -r '.status|.conditions[]|.status' | grep False | wc -l
  register: asc
  until: asc.stdout == '0'
  retries: 60
  delay: 20

- name: Wait for MCE to be available
  shell: oc get mce --no-headers | awk  '{print $2}'
  register: mce_status
  until: mce_status.stdout == "Available"
  retries: 40
  delay: 10
