---
- name: Add forward and reverse DNS entry
  become: true
  block:
    - name: Add forward DNS
      ansible.builtin.lineinfile:
        path: /var/named/{{ env.cluster.networking.metadata_name }}.db
        insertafter: ";entries for the compute nodes"
        line: "{{ param_dns_hostname }}.{{ env.cluster.networking.metadata_name }}.{{ env.cluster.networking.base_domain }}. IN A {{ param_dns_ip }}"
        state: present

    - name: Add reverse DNS
      ansible.builtin.lineinfile:
        path: /var/named/{{ env.cluster.networking.metadata_name }}.rev
        insertafter: "PTR Record IP address to Hostname"
        line: "{{ param_dns_ip.split('.').3 }}     IN      PTR     {{ param_dns_hostname }}.{{ env.cluster.networking.metadata_name }}.{{ env.cluster.networking.base_domain }}."
        state: present
