---

- name: Change permissive domain for haproxy
  tags: selinux,haproxy
  selinux_permissive:
    name: haproxy_t
    permissive: true

- name: Use template to create haproxy config file
  tags: haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    backup: yes
    force: yes

- name: Add control node information to 6443 section in haproxy config
  tags: haproxy
  lineinfile:
    line: "  server {{ env.cluster.nodes.control.hostname[i] }} {{ env.cluster.nodes.control.hostname[i] }}.{{ env.cluster.networking.metadata_name }}.{{ env.cluster.networking.base_domain }}:6443 check inter 1s"
    path: /etc/haproxy/haproxy.cfg
    insertafter: "6443 section"
  with_sequence: start=0 end={{(env.cluster.nodes.control.hostname | length) - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i

- name: Add control node information to 22623 section in haproxy config
  tags: haproxy
  lineinfile:
    line: "  server {{ env.cluster.nodes.control.hostname[i] }} {{ env.cluster.nodes.control.hostname[i] }}.{{ env.cluster.networking.metadata_name }}.{{ env.cluster.networking.base_domain }}:22623 check inter 1s"
    path: /etc/haproxy/haproxy.cfg
    insertafter: "22623 section"
  with_sequence: start=0 end={{(env.cluster.nodes.control.hostname | length) - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i

- name: Add control node information to 443 section in haproxy config, when no compute nodes are defined
  tags: haproxy
  lineinfile:
    line: "  server {{ env.cluster.nodes.control.hostname[i] }} {{ env.cluster.nodes.control.hostname[i] }}.{{ env.cluster.networking.metadata_name }}.{{ env.cluster.networking.base_domain }}:443 check inter 1s"
    path: /etc/haproxy/haproxy.cfg
    insertafter: "443 section"
  with_sequence: start=0 end={{(env.cluster.nodes.control.hostname | length) - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i
  when: env.cluster.nodes.compute.hostname is not defined

- name: Add compute node information to 443 section in haproxy config
  tags: haproxy
  lineinfile:
    line: "  server {{ env.cluster.nodes.compute.hostname[i] }} {{ env.cluster.nodes.compute.hostname[i] }}.{{ env.cluster.networking.metadata_name }}.{{ env.cluster.networking.base_domain }}:443 check inter 1s"
    path: /etc/haproxy/haproxy.cfg
    insertafter: "443 section"
  with_sequence: start=0 end={{(env.cluster.nodes.compute.hostname | length) - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i
  when: env.cluster.nodes.compute.hostname is defined

- name: Add infrastructure node information to 443 section in haproxy config
  tags: haproxy
  lineinfile:
    line: "  server {{ env.cluster.nodes.infra.hostname[i] }} {{ env.cluster.nodes.infra.hostname[i] }}.{{ env.cluster.networking.metadata_name }}.{{ env.cluster.networking.base_domain }}:443 check inter 1s"
    path: /etc/haproxy/haproxy.cfg
    insertafter: "443 section"
  with_sequence: start=0 end={{(env.cluster.nodes.infra.hostname | length) - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i
  when: env.cluster.nodes.infra.hostname is defined

- name: Add control node information to 80 section in haproxy config, when no compute nodes are defined
  tags: haproxy
  lineinfile:
    line: "  server {{ env.cluster.nodes.control.hostname[i] }} {{ env.cluster.nodes.control.hostname[i] }}.{{ env.cluster.networking.metadata_name }}.{{ env.cluster.networking.base_domain }}:80 check inter 1s"
    path: /etc/haproxy/haproxy.cfg
  with_sequence: start=0 end={{(env.cluster.nodes.control.hostname | length) - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i
  when: env.cluster.nodes.compute.hostname is not defined

- name: Add compute node information to 80 section in haproxy config
  tags: haproxy
  lineinfile:
    line: "  server {{ env.cluster.nodes.compute.hostname[i] }} {{ env.cluster.nodes.compute.hostname[i] }}.{{ env.cluster.networking.metadata_name }}.{{ env.cluster.networking.base_domain }}:80 check inter 1s"
    path: /etc/haproxy/haproxy.cfg
  with_sequence: start=0 end={{(env.cluster.nodes.compute.hostname | length) - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i
  when: env.cluster.nodes.compute.hostname is defined

- name: Add infrastructure node information to 80 section in haproxy config
  tags: haproxy
  lineinfile:
    line: "  server {{ env.cluster.nodes.infra.hostname[i] }} {{ env.cluster.nodes.infra.hostname[i] }}.{{ env.cluster.networking.metadata_name }}.{{ env.cluster.networking.base_domain }}:80 check inter 1s"
    path: /etc/haproxy/haproxy.cfg
  with_sequence: start=0 end={{(env.cluster.nodes.infra.hostname | length) - 1}} stride=1
  loop_control:
    extended: yes
    index_var: i
  when: env.cluster.nodes.infra.hostname is defined

- name: Set haproxy boolean to enable connections
  tags: haproxy
  command: setsebool -P haproxy_connect_any 1

- name: Enable haproxy
  tags: haproxy
  ansible.builtin.systemd:
    name: haproxy
    enabled: yes

- name: Restart haproxy
  tags: haproxy
  systemd:
    state: restarted
    name: haproxy
