---
- name: Almost there! Add host info to /etc/hosts so you can login to the cluster via web browser. Ansible Controller sudo password required
  tags: wait_for_install_complete
  become: true
  blockinfile:
    create: true
    backup: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR OCP CLUSTER: {{ metadata_name }}"
    path: /etc/hosts
    block: |
      {{ hostvars['bastion'].bastion_ip }} oauth-openshift.apps.{{ metadata_name }}.{{ base_domain }}
      {{ hostvars['bastion'].bastion_ip }} console-openshift-console.apps.{{ metadata_name }}.{{ base_domain }}
      {{ hostvars['bastion'].bastion_ip }} api.{{ metadata_name }}.{{ base_domain }}
  delegate_to: controller

- name: Get OCP URL
  tags: wait_for_install_complete
  set_fact:
    ocp_url: https://console-openshift-console.apps.{{ metadata_name }}.{{ base_domain }}

- name: Get OCP temporary password
  tags: wait_for_install_complete
  command: "cat /root/ocpinst/auth/kubeadmin-password"
  register: ocp_pass
  changed_when: false

- name: "Additional step, if using NAT"
  tags: wait_for_install_complete
  vars:
    nat_hypervisor_any: groups['hypervisors'] | map('extract', hostvars, ['network_mode']) | map('upper') | select('equalto', 'NAT') | list | length > 0
  debug: 
    msg: "NAT USERS ONLY: Create SSH tunnel to cluster, i.e run command in terminal window from controller: 'sshuttle -r {{ hostvars['bastion'].bastion_user }}@{{ hostvars['bastion'].bastion_ip }} 192.168.122.0/15 --dns'"
  when: nat_hypervisor_any
  changed_when: false

- name: Congratulations! OpenShift installation complete. Use the information below for first-time login via web browser.
  tags: wait_for_install_complete
  command: "echo {{ item }}"
  loop:
    - " URL: {{ ocp_url }} "
    - " Username: kubeadmin "
    - " Password: {{ ocp_pass.stdout }} "
  changed_when: false
