site_name: Ansible-Automated OpenShift Provisioning on KVM on IBM zSystems / LinuxONE
repo_url: https://github.com/IBM/Ansible-OpenShift-Provisioning
site_url: https://ibm.github.io/Ansible-OpenShift-Provisioning/
edit_uri: edit/main/docs

nav: 
  - Home: 'index.md'
  - Read Me:
    - Before You Begin: 'before-you-begin.md'
    - Prerequisites: 'prerequisites.md'
  - Installation Instructions:
    - 1 Get Info: 'get-info.md'
    - 2 Set Variables:
      - Overview: 'vars/overview.md'
      - All: 'vars/all.md'
      - Controller: 'vars/controller.md'
      - Bastion: 'vars/bastion.md'
      - File Server: 'vars/file-server.md'
      - Jumphost: 'vars/jumphost.md'
      - Hypervisors: 'vars/hypervisors.md'
      - Cluster: 'vars/cluster.md'
      - HyperShift (Optional): 'vars/hypershift.md'
    - 3 Setup Ansible Vault: 'setup-vault.md'
    - 4 Run the Playbooks:
      - Overview: 'run/overview.md'
      - 0 Setup: 'run/0-setup.md'
      - 1 Create LPARs: 'run/1-create-lpars.md'
      - 2 Create Hypervisors: 'run/2-create-hypervisors.md'
      - 3 Setup Hypervisors: 'run/3-setup-hypervisors.md'
      - 4 Create Bastion: 'run/4-create-bastion.md'
      - 5 Setup Bastion: 'run/5-setup-bastion.md'
      - 6 Create Nodes: 'run/6-create-nodes.md'
      - 7 OCP Verification: 'run/7-ocp-verification.md'
      - HyperShift: 'run/hypershift.md'
      - Site (Master Playbook): 'run/site.md'
      - Pre-Existing Site: 'run/pre-existing-site.md'
      - Reinstall Cluster: 'run/reinstall-cluster.md'
      - Add/Delete Compute Nodes: 'run/add-del-comp-nodes.md'
      - Test: 'run/test.md'
  - Misc:
    - Troubleshooting: 'troubleshooting.md'
    - Acknowledgements: 'acknowledgements.md'

theme:
  name: readthedocs
  palette:
    scheme: default
    primary: black
    font:
      text: IBM Plex Sans
      code: IBM Plex Mono
  favicon: images/ansible-logo.png
  logo: images/ansible-logo.png

copyright: Copyright © 2022 IBM zSystems Washington Systems Center

markdown_extensions:
  - fenced_code
  - codehilite
  - toc:
      permalink: "#"
  - attr_list
      
