---
- name: Ensure the PXE boot directory exists
  ansible.builtin.file:
    path: /var/lib/libvirt/images/pxeboot
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Generate param files
  ansible.builtin.template:
    src: param-file.param.j2
    dest: ~/{{ abi.ansible_workdir }}/{{ env.cluster.networking.metadata_name }}-{{ item }}.param
    mode: '644'
  with_sequence: start=0 end={{ (zvm.nodes | length) - 1 }} stride=1
  loop_control:
    extended: true
    index_var: item

- name: Copy rootfs.img
  ansible.builtin.copy:
    src: "~/{{ abi.ansible_workdir }}/boot-artifacts/agent.{{ ansible_architecture }}-rootfs.img"
    dest: /var/www/html/rootfs.img
    mode: '745'
    remote_src: true

- name: Copy initrd.img
  ansible.builtin.copy:
    src: "~/{{ abi.ansible_workdir }}/boot-artifacts/agent.{{ ansible_architecture }}-initrd.img"
    dest: /var/lib/libvirt/images/pxeboot/initrd.img
    mode: '745'
    remote_src: true

- name: Copy kernel.img
  ansible.builtin.copy:
    src: "~/{{ abi.ansible_workdir }}/boot-artifacts/agent.{{ ansible_architecture }}-kernel.img"
    dest: /var/lib/libvirt/images/pxeboot/kernel.img
    mode: '745'
    remote_src: true
