examples:
   api_version:
      hmc: 9.60.86.110
      verify_cert: false
   show_os_messages:
      hmc: 9.60.86.110
      cpcname: P0007DE8
      partname: Distrib-KVM01
      verify_cert: false
"9.60.86.110":
   userid: jacob.emery@ibm.com
   password: vpb-ubp_CGZ9cnz8ctk
   verify_cert: false
cpcs:
   P0007DE8:
      hmc_host: 9.60.86.110
      hmc_userid: jacob.emery@ibm.com
      hmc_password: vpb-ubp_CGZ9cnz8ctk
      verify_cert: false 
