---

- name: Set up macvtap bridge configuration xml from template to KVM host
  tags: macvtap
  community.libvirt.virt_net:
    command: define
    name: "{{ env.vnet_name }}"
    xml: "{{ lookup ('template', 'macvtap.xml.j2') }}"

- name: Start macvtap bridge
  tags: macvtap
  community.libvirt.virt_net:
    command: start
    name: "{{ env.vnet_name }}"

- name: Set macvtap bridge to autostart
  tags: macvtap
  community.libvirt.virt_net:
    autostart: yes
    name: "{{ env.vnet_name }}"
