---
- name: Getting Hosted Control Plane Namespace
  set_fact: 
    hosted_control_plane_namespace: "{{ hypershift.hcp.clusters_namespace }}-{{ hypershift.hcp.hosted_cluster_name }}"

- name: Check if Hosted Control Plane Namespace exists 
  k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ hosted_control_plane_namespace }}"
  register: namespace_check
  ignore_errors: yes

- name: Create Hosted Control Plane Namespace 
  k8s:
    api_version: v1
    kind: Namespace
    name: "{{ hosted_control_plane_namespace }}"
    state: present
  when: namespace_check.resources | length == 0 

- name: Get ssh key 
  ansible.builtin.shell: cat ~/.ssh/{{ env.ansible_key_name }}.pub
  register: ssh_output
 
- name: Load ssh_key into a variable
  set_fact:
    ssh_key: "{{ ssh_output.stdout_lines[0] }}"

- name: Create a Hosted Cluster
  command: >
    hypershift create cluster agent 
    --name={{ hypershift.hcp.hosted_cluster_name }} 
    --pull-secret={{ hypershift.hcp.pull_secret_file }} 
    --agent-namespace={{ hosted_control_plane_namespace }} 
    --namespace={{ hypershift.hcp.clusters_namespace }} 
    --base-domain= {{ hypershift.hcp.basedomain }} 
    --api-server-address=api.{{ hypershift.hcp.hosted_cluster_name }}.{{ hypershift.hcp.basedomain }} 
    --ssh-key ~/.ssh/{{ env.ansible_key_name }}.pub
    --release-image=quay.io/openshift-release-dev/ocp-release:{{ hypershift.hcp.ocp_release }} 
    {% set release_image = lookup('env', 'HCP_RELEASE_IMAGE') %}
    {% if release_image is defined and release_image != '' %}
    --release-image={{ release_image }}
    {% else %}
    --release-image=quay.io/openshift-release-dev/ocp-release:{{ hypershift.hcp.ocp_release }}
    {% endif %}

- name: Waiting for Hosted Control Plane to be available
  command: oc wait --timeout=30m --for=condition=Available --namespace={{ hypershift.hcp.clusters_namespace }} hostedcluster/{{ hypershift.hcp.hosted_cluster_name }}

- name: Wait for pods to come up in Hosted Cluster Namespace
  shell: oc get pods -n {{ hosted_control_plane_namespace }} | wc -l
  register: pod_count
  until: pod_count.stdout | int > 30
  retries: 40
  delay: 10

- name: Wait for all pods to be in Running State in  Hosted Cluster Namespace
  shell: oc get pods -n {{ hosted_control_plane_namespace }}  --no-headers | grep -v 'Running\|Completed\|Terminating' | wc -l
  register: pod_status
  until: pod_status.stdout == '0'
  retries: 30
  delay: 10

- name: Create InfraEnv.yaml
  template:
    src: InfraEnv.yaml.j2
    dest: /root/ansible_workdir/InfraEnv.yaml

- name: Deploy InfraEnv Resource
  command: oc apply -f /root/ansible_workdir/InfraEnv.yaml

- name: Creating list of mac addresses
  set_fact:
    agent_mac_addr: []
  when: hypershift.agents_parms.static_ip_parms.static_ip == true

- name: Getting mac addresss for agents
  set_fact:
    agent_mac_addr: "{{ hypershift.agents_parms.agent_mac_addr }}"
  when: ( hypershift.agents_parms.static_ip_parms.static_ip == true ) and ( hypershift.agents_parms.agent_mac_addr != None )

- name: Generate mac addresses for agents
  set_fact:
    agent_mac_addr: "{{ agent_mac_addr +  ['52:54:00' | community.general.random_mac] }}"
  when: ( hypershift.agents_parms.static_ip_parms.static_ip == true ) and ( hypershift.agents_parms.agent_mac_addr == None )
  loop: "{{ range(hypershift.agents_parms.agents_count|int) | list }}"

- name: Create NMState Configs
  template:
    src:  nmStateConfig.yaml.j2
    dest: /root/ansible_workdir/nmStateConfig-agent-{{ item }}.yaml
  when: hypershift.agents_parms.static_ip_parms.static_ip == true
  loop: "{{ range(hypershift.agents_parms.agents_count|int) | list }}"

- name: Deploy NMState Configs
  command: oc apply -f /root/ansible_workdir/nmStateConfig-agent-{{ item }}.yaml
  when: hypershift.agents_parms.static_ip_parms.static_ip == true
  loop: "{{ range(hypershift.agents_parms.agents_count|int) | list }}"

- name: Wait for ISO to generate in InfraEnv 
  shell: oc get InfraEnv -n  {{ hosted_control_plane_namespace }} --no-headers
  register: infra
  until: infra.stdout.split(' ')[-1] != ''
  retries: 60
  delay: 20
