---
param_compute_node:
  # node_vm_name:
  # node_vm_hostname:
  # hypervisor_name:
  # hypervisor_user:
  # hypervisor_arch:
  # vcpu:
  # memory:
  # vcpu_model_option:
  # networking:
  #   ip:
  #   ipv6:
  #   gateway:
  #   ipv6_gateway:
  #   subnetmask:
  #   ipv6_prefix:
  #   mac_address:
  #   device:
