hcp:
  # Parameters for oc login
  mgmt_cluster_nameserver: 172.23.232.140
  oc_url: https://api.shwe-lpar-hub-roce.shwe-hcpvirt.com:6443

  mgmt_cluster_bastion:
    ip: 172.23.232.140              # Your bastion IP
    user: root                      # SSH user
    password: "{{ bastion_root_pw }}"

  ansible_key_name: ansible-ocpz

  # MultiClusterEngine Parameters
  mce:
    version:  # Mention if specific version is needed, otherwise the latest stable version will be installed
    delete: false
    catalogsource_image: "quay.io:443/acm-d/mce-dev-catalog:v2.11.0-162"   # Required only if we need to create the Catalogsource for installing MCE

  #MetalLB Parameters
  metallb:
    version: stable
    delete: false
    ip_pool: #minimum 2 free IPs are required in the subnet for MetalLB to work properly. You can provide a single IP or a range of IPs in string format or a list of IPs/IP ranges. For example:
    - 172.23.232.141-172.23.232.142
    - #172.23.232.140-172.23.232.140
    - #172.23.232.140-172.23.232.142

  # OpenShift Virtualization Parameters
  ocpvirt:
    version: stable
    delete: false

  # Local Storage Operator Parameters
  lso:
    version: stable
    delete: false
    storage_nodes:
      - control-0
      - control-1
      - control-2
    localvolume:
      device_paths:
        - /dev/disk/by-id/wwn-0x600507630affd0a40000000000000160
        - /dev/disk/by-id/wwn-0x600507630affd0a40000000000000161
        - /dev/disk/by-id/wwn-0x600507630affd0a40000000000000162

  #ODF Parameters
  odf:
    version: stable-4.20
    storage: 500Gi

  # Hosted Control Plane Parameters
  control_plane:
    high_availability: true
    clusters_namespace:
    hosted_cluster_name:
    basedomain:
    ocp_release_image:
    arch: s390x
    additional_flags:
    # Make sure to enclose pull_secret in 'single quotes'
    pull_secret:

  data_plane:
    compute_count:
    vcpus: 4
    memory: 16384
