---

- name: Destroy Agent VMs
  command: virsh destroy {{ hcp.control_plane.hosted_cluster_name }}-agent-{{ item }} 
  loop: "{{ range(hcp.data_plane.compute_count|int) | list }}"

- name: Undefine Agents
  command: virsh undefine {{ hcp.control_plane.hosted_cluster_name }}-agent-{{ item }} --remove-all-storage
  loop: "{{ range(hcp.data_plane.compute_count|int) | list }}"

- name: Delete  initrd.img
  file:
    path: /var/lib/libvirt/images/pxeboot/initrd.img
    state: absent

- name: Delete  kernel.img
  file:
    path: /var/lib/libvirt/images/pxeboot/kernel.img
    state: absent

- name: Destroy bastion
  command: virsh destroy {{ hcp.control_plane.hosted_cluster_name }}-bastion

- name: Undefine bastion
  command: virsh undefine {{ hcp.control_plane.hosted_cluster_name }}-bastion --remove-all-storage
