---
- name: Check internal cluster DNS resolution for the bastion.
  tags: check_dns, dns
  shell: "dig +short {{ hostvars['bastion'].fqdn }} | tail -n1"
  register: bastion_lookup
  failed_when: hostvars['bastion'].bastion_ip != bastion_lookup.stdout
  changed_when: false

- name: Print results of 'check internal cluster DNS resolution for the bastion'.
  tags: check_dns, dns
  debug:
    msg: "{{ hostvars['bastion'].fqdn.split('.')[0] }} - from inventory: {{ hostvars['bastion'].bastion_ip }}, from DNS: {{ bastion_lookup.stdout }}"

- name: Check DNS resolution for all nodes.
  tags: check_dns, dns
  shell: "dig +short {{ hostvars[node].hostname }}.{{ metadata_name }}.{{ base_domain }} | tail -n1"
  register: node_lookup
  loop: "{{ [hostvars['bootstrap_node'].inventory_hostname] + groups['control_nodes'] + groups['compute_nodes']  }}"
  loop_control:
    loop_var: node
    label: "{{ hostvars[node].hostname }} - from inventory: {{ hostvars[node].node_ip }}, from DNS: {{ node_lookup.stdout }}"
  failed_when: hostvars[node].node_ip != node_lookup.stdout
  changed_when: false

- name: Check internal cluster DNS resolution for external API and apps services.
  tags: check_dns, dns
  shell: "dig +short {{ item }} | tail -n1"
  loop:
    - "api.{{ metadata_name }}.{{ base_domain }}"
    - "apps.{{ metadata_name }}.{{ base_domain }}"
    - "test.apps.{{ metadata_name }}.{{ base_domain }}"
  loop_control:
    label: >-
      {{ item }} - from inventory: {{
        hostvars['bastion'].setup_lb
        | ternary(hostvars['bastion'].bastion_ip, hostvars['bastion'].lb_public_ip)
      }},
      from DNS: {{ services_lookup.stdout }}
  register: services_lookup
  failed_when: ((hostvars['bastion'].setup_lb == True) and (hostvars['bastion'].bastion_ip != services_lookup.stdout)) or ((hostvars['bastion'].setup_lb == False) and (hostvars['bastion'].lb_public_ip != services_lookup.stdout) )
  changed_when: false

- name: Check internal cluster DNS resolution for internal API services.
  tags: check_dns, dns
  shell: "dig +short api-int.{{ metadata_name }}.{{ base_domain }} | tail -n1"
  register: api_int_lookup
  failed_when: ((hostvars['bastion'].setup_lb == True) and (hostvars['bastion'].bastion_ip != api_int_lookup.stdout)) or ((hostvars['bastion'].setup_lb == False) and (hostvars['bastion'].lb_private_ip != api_int_lookup.stdout) )
  changed_when: false

- name: Print results of 'check internal cluster DNS resolution for internal API services'.
  tags: check_dns, dns
  debug:
    msg: >-
      api-int.{{ metadata_name }}.{{ base_domain }} - from inventory: {{
        hostvars['bastion'].setup_lb
        | ternary(hostvars['bastion'].bastion_ip, hostvars['bastion'].lb_private_ip)
      }},
      from DNS: {{ api_int_lookup.stdout }}

- name: Check external DNS resolution from forwarder.
  tags: check_dns, dns
  register: external_dns_check
  command: "nslookup {{ item }}"
  loop:
    - www.google.com
    - www.ibm.com
    - www.redhat.com
  failed_when: '"server can" in external_dns_check.stdout'
  changed_when: false
