---

- name: Create directory in <storage.pool_path> for this cluster's storage pool.
  tags: configure_storage, pool
  ansible.builtin.file:
    path: "{{ storage.pool_path }}/{{ env.cluster.networking.metadata_name }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: qemu
    seuser: system_u
    setype: virt_image_t
    mode: '0770'
    recurse: true

- name: Ensure qemu has execute permissions for all parent directories of the directory that will be used as a storage pool for this cluster.
  tags: configure_storage, pool
  ansible.builtin.file:
    path: "{{ storage.pool_path.split('/')[:i] | join('/') }}"
    state: directory
    group: qemu
    mode: g+x
    recurse: false
  loop: "{{ range(0, storage.pool_path.split('/') | length + 1) | list }}"
  loop_control:
    extended: true
    index_var: i
    extended_allitems: false
    label: "{{ storage.pool_path.split('/')[:i] | join('/') }}"
  when: "storage.pool_path.split('/')[:i] | join('/') != ''"

- name: Define a new storage pool
  tags: configure_storage, pool
  community.libvirt.virt_pool:
    command: define
    name: "{{ env.cluster.networking.metadata_name }}-vdisk"
    xml: '{{ lookup("template", "vdisk.xml.j2") }}'

- name: Set storage pool to active.
  tags: configure_storage, pool
  community.libvirt.virt_pool:
    name: "{{ env.cluster.networking.metadata_name }}-vdisk"
    state: active

- name: Set storage pool to autostart.
  tags: configure_storage, pool
  community.libvirt.virt_pool:
    name: "{{ env.cluster.networking.metadata_name }}-vdisk"
    autostart: true
