---
- name: List all VMs
  community.libvirt.virt:
      command: list_vms
  register: all_vms

- name: List only running VMs
  community.libvirt.virt:
    command: list_vms
    state: running
  register: running_vms

- name: Destroy Agent VMs
  ansible.builtin.command: virsh destroy {{ hcp.control_plane.hosted_cluster_name }}-agent-{{ item }} 
  loop: "{{ range(hcp.data_plane.compute_count|int) | list }}"
  when: "{{ hcp.control_plane.hosted_cluster_name }}-agent-{{ item }} in all_vms.list_vms"

- name: Undefine the Agents
  ansible.builtin.command: virsh undefine {{ hcp.control_plane.hosted_cluster_name }}-agent-{{ item }} --remove-all-storage
  loop: "{{ range(hcp.data_plane.compute_count|int) | list }}"
  when: "{{ hcp.control_plane.hosted_cluster_name }}-agent-{{ item }} in running_vms.list_vms"

- name: Delete the initrd.img
  ansible.builtin.file:
    path: /var/lib/libvirt/images/pxeboot/initrd.img
    state: absent
  when: ( hcp.data_plane.kvm.boot_method | lower != 'iso' and hcp.compute_node_type | lower == 'kvm' ) or hcp.compute_node_type | lower != 'kvm'

- name: Delete the kernel.img
  ansible.builtin.file:
    path: /var/lib/libvirt/images/pxeboot/kernel.img
    state: absent
  when: ( hcp.data_plane.kvm.boot_method | lower != 'iso' and hcp.compute_node_type | lower == 'kvm' ) or hcp.compute_node_type | lower != 'kvm'

- name: Delete ISO
  ansible.builtin.file:
    path: /var/lib/libvirt/images/pxeboot/image.iso
    state: absent
  when: hcp.data_plane.kvm.boot_method | lower == 'iso' and hcp.compute_node_type | lower == 'kvm'

- name: Destroy Bastion
  ansible.builtin.command: virsh destroy {{ hcp.control_plane.hosted_cluster_name }}-bastion
  when: "{{ hcp.control_plane.hosted_cluster_name }}-agent-{{ item }} in all_vms.list_vms"

- name: Undefine Bastion
  ansible.builtin.command: virsh undefine {{ hcp.control_plane.hosted_cluster_name }}-bastion --remove-all-storage
  when: "{{ hcp.control_plane.hosted_cluster_name }}-agent-{{ item }} in running_vms.list_vms"

- name: Stop the storage pool
  community.libvirt.virt_pool:
    name: "{{ hcp.control_plane.hosted_cluster_name }}-vdisk"
    state: inactive
  when: hcp.data_plane.kvm.storage.type | lower  != 'dasd' and hcp.compute_node_type | lower == 'kvm'

- name: Delete the storage pool
  community.libvirt.virt_pool:
    name: "{{ hcp.control_plane.hosted_cluster_name }}-vdisk"
    state: absent
  when: hcp.data_plane.kvm.storage.type | lower  != 'dasd' and hcp.compute_node_type | lower == 'kvm'

- name: Delete directory created for Storage pool
  ansible.builtin.file:
    path: "{{ hcp.data_plane.kvm.storage.qcow.pool_path }}{{ hcp.control_plane.hosted_cluster_name }}"
    state: absent
  when: hcp.data_plane.kvm.storage.type | lower  != 'dasd' and hcp.compute_node_type | lower == 'kvm'