---

- name: Destroy Agent VMs
  command: virsh destroy {{ hcp.control_plane.hosted_cluster_name }}-agent-{{ item }} 
  loop: "{{ range(hcp.data_plane.compute_count|int) | list }}"

- name: Undefine the Agents
  command: virsh undefine {{ hcp.control_plane.hosted_cluster_name }}-agent-{{ item }} --remove-all-storage
  loop: "{{ range(hcp.data_plane.compute_count|int) | list }}"

- name: Delete the initrd.img
  file:
    path: /var/lib/libvirt/images/pxeboot/initrd.img
    state: absent
  when: ( hcp.data_plane.kvm.boot_method | lower != 'iso' and hcp.compute_node_type | lower == 'kvm' ) or hcp.compute_node_type | lower != 'kvm'

- name: Delete the kernel.img
  file:
    path: /var/lib/libvirt/images/pxeboot/kernel.img
    state: absent
  when: ( hcp.data_plane.kvm.boot_method | lower != 'iso' and hcp.compute_node_type | lower == 'kvm' ) or hcp.compute_node_type | lower != 'kvm'

- name: Delete ISO
  file:
    path: /var/lib/libvirt/images/pxeboot/image.iso
    state: absent
  when: hcp.data_plane.kvm.boot_method | lower == 'iso' and hcp.compute_node_type | lower == 'kvm'

- name: Destroy Bastion
  command: virsh destroy {{ hcp.control_plane.hosted_cluster_name }}-bastion

- name: Undefine Bastion
  command: virsh undefine {{ hcp.control_plane.hosted_cluster_name }}-bastion --remove-all-storage

- name: Stop the storage pool
  community.libvirt.virt_pool:
    name: "{{ hcp.control_plane.hosted_cluster_name }}-vdisk"
    state: inactive
  when: hcp.data_plane.kvm.storage.type | lower  != 'dasd' and hcp.compute_node_type | lower == 'kvm'

- name: Delete the storage pool
  community.libvirt.virt_pool:
    name: "{{ hcp.control_plane.hosted_cluster_name }}-vdisk"
    state: absent
  when: hcp.data_plane.kvm.storage.type | lower  != 'dasd' and hcp.compute_node_type | lower == 'kvm'

- name: Delete directory created for Storage pool
  ansible.builtin.file:
    path: "{{ hcp.data_plane.kvm.storage.qcow.pool_path }}{{ hcp.control_plane.hosted_cluster_name }}"
    state: absent
  when: hcp.data_plane.kvm.storage.type | lower  != 'dasd' and hcp.compute_node_type | lower == 'kvm'
