---

- name: Check to see if local SSH directory exists
  tags: ssh_key_gen, ssh
  stat:
    path: "~/.ssh"
  register: ssh_directory_exists_check

- name: Create SSH local directory if it doesn't already exist
  tags: ssh_key_gen, ssh
  file:
    path: "~/.ssh"
    state: directory
    mode: '700'
  register: ssh_directory_creation
  when: ssh_directory_exists_check.stat.exists == false

- name: Generate an OpenSSH keypair with the default values (4096 bits, RSA)
  tags: ssh_key_gen, ssh
  community.crypto.openssh_keypair:
    path: "{{ hostvars[ssh_target].ansible_ssh_private_key_file }}"
    passphrase: ""
    comment: "Ansible-OpenShift-Provisioning SSH key"
    regenerate: never
  register: ssh_key_creation

- name: Print results of ssh key pair creation
  tags: ssh_key_gen, ssh
  debug:
    var: ssh_key_creation
