---

- name: Create Logical Partitions (LPARs).
  tags: create_lpar, lpar
  ibm.ibm_zhmc.zhmc_partition:
    cpc_name: "{{ cpc_name }}"
    hmc_host: "{{ hmc_host }}"
    hmc_auth: 
      userid: "{{ hmc_user }}"
      password: "{{ hmc_pass }}"
      verify: false
    name: "{{ lpar_name }}"
    state: stopped
    properties:
      description: "{{ lpar_desc }}"
      ifl_processors: "{{ ifl_count }}"
      initial_memory: "{{ mem_init }}"
      maximum_memory: "{{ mem_max }}"
      minimum_ifl_processing_weight: "{{ weight_min }}"
      maximum_ifl_processing_weight: "{{ weight_max }}"
      initial_ifl_processing_weight: "{{ weight_init }}"
  register: create_lpar

- name: Print the result
  tags: create_lpar, lpar
  debug:
    var: create_lpar

- name: Attach storage groups to partition.
  tags: create_lpar, storage_groups
  ibm.ibm_zhmc.zhmc_storage_group_attachment:
    cpc_name: "{{ cpc_name }}"
    hmc_host: "{{ hmc_host }}"
    hmc_auth: 
      userid: "{{ hmc_user }}"
      password: "{{ hmc_pass }}"
      verify: false
    partition_name: "{{ lpar_name  }}"
    storage_group_name: "{{ item.name }}"
    state: attached
  loop: "{{ storage_groups }}"
  register: storage_groups

- name: Print the result.
  tags: create_lpar, storage_groups
  debug:
    var: storage_groups

- name: Attach Network Interface Cards (NICs) to partition.
  tags: create_lpar, nics
  ibm.ibm_zhmc.zhmc_nic:
    cpc_name: "{{ cpc_name }}"    
    hmc_host: "{{ hmc_host }}"
    hmc_auth: 
      userid: "{{ hmc_user }}"
      password: "{{ hmc_pass }}"
      verify: false
    partition_name: "{{ lpar_name }}"
    name: "{{ item.name }}"
    state: present 
    properties:
      adapter_name: "{{ item.adapter }}"
      adapter_port: "{{ item.port }}"
      description: "{{ item.name }}"
      device_number: "{{ '%04x' % item.dev_num | int }}"
  loop: "{{ nics }}"
  register: nics  

- name: Print the results.
  tags: create_lpar, nics
  debug:
    var: nics
