---
- name: Print the list of packages to be installed and updated.
  tags: install_packages
  debug: msg={{ vars[packages] }} 

- name: Getting RHEL Version
  shell: awk -F 'release ' '{print $2}' /etc/redhat-release | awk '{print $1}'
  register: rhel_version

- name: Installing libvirt-devel packages for Linux machines.
  tags: install_packages
  become: true
  ansible.builtin.package:
    name: "libvirt-devel"
    state: latest
    update_cache: yes
  when: ( ansible_os_family != 'Darwin') and ( rhel_version.stdout| float < 9.0 )

- name: Installing required packages for Linux machines.
  tags: install_packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ vars[packages] }}"
  when: ansible_os_family != 'Darwin'

- name: Installing required packages for Mac machines.
  tags: install_packages
  become: false
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  loop: "{{ vars[packages] }}"
  when: ansible_os_family == 'Darwin'
