---
- name: Print the list of packages to be installed and updated.
  tags: install_packages
  debug:
    var: pkgs

- name: Installing required packages for Linux machines.
  tags: install_packages
  become: true
  ansible.builtin.package:
    name: "{{ pkgs }}"
    state: latest
    update_cache: yes
  when: ansible_system == 'Linux'

- name: Installing required packages for Mac machines.
  tags: install_packages
  become: false
  community.general.homebrew:
    name: "{{ pkgs }}"
    state: latest
  when: ansible_system == 'Darwin'
