---
- name: Print the list of packages to be installed and updated.
  tags: install_packages
  debug: msg={{ vars[packages] }} 

- name: Getting OS Version
  shell: cat /etc/*release | grep 'VERSION_ID' | cut -d "=" -f 2 | tr -d '"'
  register: os_version

- name: Installing libvirt-devel packages for RHEL machines.
  tags: install_packages
  become: true
  ansible.builtin.package:
    name: "libvirt-devel"
    state: latest
    update_cache: yes
  when: ( ansible_os_family | lower == 'redhat') and ( os_version.stdout| float < 9.0 )

- name: Installing required packages for Linux machines.
  tags: install_packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ vars[packages] }}"
  when: ansible_os_family != 'Darwin'

- name: Installing required packages for Mac machines.
  tags: install_packages
  become: false
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  loop: "{{ vars[packages] }}"
  when: ansible_os_family == 'Darwin'
