---

- name: Create Agent Using PXE Boot (fips = false)
  ansible.builtin.command: openshift-install agent create pxe-files --log-level=debug
  args:
    chdir: ~/{{ abi.ansible_workdir }}
  when: abi.boot_method | lower == "pxe" and not install_config_vars.fips

- name: Create Agent Using ISO Image (fips = false)
  ansible.builtin.command: openshift-install agent create image --log-level=debug
  args:
    chdir: ~/{{ abi.ansible_workdir }}
  when: abi.boot_method | lower == "iso" and not install_config_vars.fips

- name: Create Agent Using PXE Boot (fips = true)
  ansible.builtin.command: openshift-install-fips agent create pxe-files --log-level=debug
  args:
    chdir: ~/{{ abi.ansible_workdir }}
  when: abi.boot_method | lower == "pxe" and install_config_vars.fips

- name: Create Agent Using ISO Image (fips = true)
  ansible.builtin.command: openshift-install-fips agent create image --log-level=debug
  args:
    chdir: ~/{{ abi.ansible_workdir }}
  when: abi.boot_method | lower == "iso" and install_config_vars.fips

- name: Copy initrd.img, vmlinuz, and rootfs.img for PXE
  ansible.builtin.copy:
    src: "~/{{ abi.ansible_workdir }}/boot-artifacts/"
    dest: /var/www/html/
    mode: '645'
    remote_src: true
  when: abi.boot_method | lower == "pxe"

- name: Check if vmlinuz exists in /var/www/html
  stat:
    path: "/var/www/html/agent.{{ ansible_architecture }}-vmlinuz"
  register: vmlinuz_www

- name: Create kernel.img as copy of vmlinuz for backward compatibility
  ansible.builtin.copy:
    src: "/var/www/html/agent.{{ ansible_architecture }}-vmlinuz"
    dest: /var/www/html/agent.{{ ansible_architecture }}-kernel.img
    mode: '644'
    remote_src: true
  when: abi.boot_method | lower == "pxe" and vmlinuz_www.stat.exists

- name: Copy ISO image to the server
  ansible.builtin.copy:
    src: "~/{{ abi.ansible_workdir }}/"
    dest: /var/www/html/
    mode: '645'
    remote_src: true
  when: abi.boot_method | lower == "iso"
