---
- name: Create Installation directory
  file:
    path: /var/lib/libvirt/images/pxeboot
    state: directory
    mode: '0755'

- name: Get URL for initrd.img
  shell: oc -n "{{ hcp.control_plane.hosted_cluster_name }}-agents" get InfraEnv "{{ hcp.control_plane.hosted_cluster_name }}" -ojsonpath="{.status.bootArtifacts.initrd}"
  register: initrd
  when: ( hcp.data_plane.kvm.boot_method | lower != 'iso' and hcp.compute_node_type | lower == 'kvm' ) or hcp.compute_node_type | lower != 'kvm'

- name: Download initrd.img
  get_url:
    url: "{{ initrd.stdout }}"
    dest: /var/lib/libvirt/images/pxeboot/initrd.img
    validate_certs: false
  when: ( hcp.data_plane.kvm.boot_method | lower != 'iso' and hcp.compute_node_type | lower == 'kvm' ) or hcp.compute_node_type | lower != 'kvm'

- name: Get URL for kernel.img
  shell: oc -n "{{ hcp.control_plane.hosted_cluster_name }}-agents" get InfraEnv "{{ hcp.control_plane.hosted_cluster_name }}" -ojsonpath="{.status.bootArtifacts.kernel}"
  register: kernel
  when: ( hcp.data_plane.kvm.boot_method | lower != 'iso' and hcp.compute_node_type | lower == 'kvm' ) or hcp.compute_node_type | lower != 'kvm'

- name: Download kernel.img
  get_url:
    url: "{{ kernel.stdout }}"
    dest: /var/lib/libvirt/images/pxeboot/kernel.img
    validate_certs: false
  when: ( hcp.data_plane.kvm.boot_method | lower != 'iso' and hcp.compute_node_type | lower == 'kvm' ) or hcp.compute_node_type | lower != 'kvm'

- name: Get URL for ISO
  shell: oc -n "{{ hcp.control_plane.hosted_cluster_name }}-agents" get InfraEnv "{{ hcp.control_plane.hosted_cluster_name }}" -ojsonpath="{.status.isoDownloadURL}"
  register: iso
  when: hcp.data_plane.kvm.boot_method | lower == 'iso' and  hcp.compute_node_type | lower == 'kvm'

- name: Download ISO image
  get_url:
    url: "{{ iso.stdout }}"
    dest: /var/lib/libvirt/images/pxeboot/image.iso
    validate_certs: false
  when: hcp.data_plane.kvm.boot_method | lower == 'iso' and  hcp.compute_node_type | lower == 'kvm'

- name: Generate param files
  template:
    src: parm-file.parm.j2
    dest: /root/ansible_workdir/agent-{{ item }}.parm
  when: hcp.compute_node_type | lower != 'kvm'
  loop: "{{ range(hcp.data_plane.compute_count | int) | list }}"
