---
- name: Get and print OCP nodes status
  block:
    - name: Get OCP nodes status
      # Print oc node status in such format:
      # NAME        STATUS                     ROLES                  AGE     VERSION           KERNEL-VERSION                INTERNAL-IP
      # master-1    Ready                      control-plane,master   35h     v1.25.4+77bec7a   4.18.0-372.40.1.el8_6.s390x   172.23.232.131
      ansible.builtin.shell: |
        set -o pipefail
        oc get nodes -o wide | awk -F '  +' '{ printf "%-24s %-26s %-22s %-7s %-17s %-29s %-15s\n", $1, $2, $3, $4, $5, $9, $6 }'
      register: oc_get_nodes
      until: oc_get_nodes.rc == 0
      retries: 3
      delay: 5
      changed_when: false

    - name: Print OCP nodes status
      ansible.builtin.debug:
        var: oc_get_nodes.stdout_lines
