---
- name: install apache httpd
  package:
    name: httpd
    state: latest

- name: bind httpd to port 8080 
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: ^Listen 80
    line: Listen 8080
    
- name: bind https to port 8443 
  lineinfile:
    dest: /etc/httpd/conf.d/ssl.conf
    regexp: ^Listen 443 https
    line: Listen 8443 https
    
- name: allow traffic at 8080 for apache 
  tags: firewall
  firewalld:
    port: 8080/tcp
    zone: "{{ item }}"
    state: enabled
    permanent: true
  with_items:
  - internal
  - public
  
- name: allow traffic at 8443 for apache 
  tags: firewall
  firewalld:
    port: 8443/tcp
    zone: "{{ item }}"
    state: enabled
    permanent: true
  with_items:
  - internal
  - public

- name: Get URL for rootfs.img
  shell: oc -n "{{ hypershift.hcp.clusters_namespace }}-{{ hypershift.hcp.hosted_cluster_name }}" get InfraEnv "{{ hypershift.hcp.hosted_cluster_name }}" -ojsonpath="{.status.bootArtifacts.rootfs}"
  register: rootfs

- name: Download rootfs.img
  get_url:
    url: "{{ rootfs.stdout }}"
    dest: /var/www/html/rootfs.img
    validate_certs: false

- name: restart httpd 
  service:
    name: httpd.service
    state: started
    enabled: yes

- name: Restart firewalld.service
  service:
    name: firewalld.service
    state: restarted
