---

- name: Get virsh list of pre-existing running nodes.
  tags: delete_nodes, shutdown
  community.libvirt.virt:
    command: list_vms
    state: running
  register: virsh_running

- name: Shutdown pre-existing running nodes.
  tags: delete_nodes, shutdown
  vars:
    nodes_on_hypervisor: "{{ guests | select('search', target_nodes) | list }}"
  community.libvirt.virt:
    name: "{{ hostvars[node].vm_name }}"
    command: destroy
  when: nodes_on_hypervisor | length > 0 and hostvars[node].vm_name in virsh_running.list_vms
  loop: "{{ nodes_on_hypervisor }}"
  loop_control:
    loop_var: node
  register: shutdown_nodes

- name: Get virsh list of pre-existing nodes.
  tags: delete_nodes, undefine
  community.libvirt.virt:
    command: list_vms
  register: virsh_defined

- name: Undefine pre-existing defined nodes.
  tags: delete_nodes, undefine
  vars:
    nodes_on_hypervisor: "{{ guests | select('search', target_nodes) | list }}"
  community.libvirt.virt:
    name: "{{ hostvars[node].vm_name }}"
    command: undefine
  when: nodes_on_hypervisor | length > 0 and hostvars[node].vm_name in virsh_defined.list_vms
  loop: "{{ nodes_on_hypervisor }}"
  loop_control:
    loop_var: node
  register: undefine_nodes

- name: Get virsh list for verification.
  tags: delete_nodes, verify
  community.libvirt.virt:
    command: list_vms
  register: virsh

- name: Print virsh list for verification.
  tags: delete_nodes, verify
  ansible.builtin.debug:
    msg: "{{ virsh.list_vms }}"