---

- name: Delete bootstrap node, if exists
  tags: delete_nodes
  ansible.builtin.shell: |
    set -o pipefail
    virsh destroy "{{ env.cluster.nodes.bootstrap.vm_name }}" || true
    virsh undefine "{{ env.cluster.nodes.bootstrap.vm_name }}" --remove-all-storage --nvram || true
  register: delete_bootstrap
  when: ( env.abi.flag is not defined ) or ( env.abi.flag != True )
  changed_when: "('destroyed' in delete_bootstrap.stdout) or ('undefined' in delete_bootstrap.stdout)"

- name: Delete control, compute and infra nodes, if exists
  tags: delete_nodes
  ansible.builtin.shell: |
    virsh destroy {{ item }} || true
    virsh undefine {{ item }} --remove-all-storage --nvram || true
  loop: "{{ (env.cluster.nodes.control.vm_name | default([]))+ \
        (env.cluster.nodes.compute.vm_name | default([])) + (env.cluster.nodes.infra.vm_name | default([])) }}"
  register: delete_nodes
  changed_when: "('destroyed' in delete_nodes.stdout) or ('undefined' in delete_nodes.stdout)"

- name: Get and print virsh list
  tags: delete_nodes
  block:
    - name: Get virsh list
      ansible.builtin.command: virsh list
      register: cmd_virsh_list

    - name: Print virsh list
      ansible.builtin.debug:
        var: cmd_virsh_list.stdout_lines
