---
- name: Checking Hosted Cluster
  ansible.builtin.command:
    cmd: oc get hc -n {{ hcp.control_plane.clusters_namespace }}
  register: hc_check

- name: Destroy Hosted Control Plane
  ansible.builtin.command:
    cmd: hcp destroy cluster kubevirt --name {{ hcp.control_plane.hosted_cluster_name }} --namespace {{ hcp.control_plane.clusters_namespace }}
  when: hcp.control_plane.hosted_cluster_name in hc_check.stdout
