---
- name: mirror artifacts in disconnected mode
  tags: mirror_artifacts
  block:
    - name: Setting Up nameserver on mirror host to resolve DNS
      ansible.builtin.template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: "644"
    - name: Get user home directory
      tags: mirror_artifacts
      shell: >
          getent passwd {{ ansible_user }} | awk -F: '{ print $6 }'
      changed_when: false
      register: user_home
    - name: Delete OCP download directory for idempotency.
      tags: mirror_artifacts
      become: true
      file:
        path: "{{ user_home.stdout }}/ocpinst_disconnected"
        state: absent
    - name: Create OCP download directory
      tags: mirror_artifacts
      file:
        path: "{{ user_home.stdout }}/ocpinst_disconnected"
        state: directory
    - name: Unzip OCP client and oc-mirror
      tags: mirror_artifacts
      ansible.builtin.unarchive:
        src: "{{ item }}"
        dest: "{{ user_home.stdout }}/ocpinst_disconnected/"
        remote_src: yes
      loop:
        - "{{ disconnected.mirroring.client_download.ocp_download_url }}{{ disconnected.mirroring.client_download.ocp_client_tgz }}"
        - "{{ env.file_server.protocol }}://{{ env.file_server.user + ':' + env.file_server.pass + '@' if env.file_server.protocol == 'ftp' else '' }}{{ env.file_server.ip }}{{ ':' + env.file_server.port if env.file_server.port | default('') | length > 0 else '' }}/{{ disconnected.mirroring.file_server.clients_dir }}/{{ disconnected.mirroring.file_server.oc_mirror_tgz }}"
    - name: Copy kubectl, oc, and oc-mirror binaries to /usr/local/sbin
      tags: mirror_artifacts
      become: true
      ansible.builtin.copy:
        src: "{{ user_home.stdout }}/ocpinst_disconnected/{{ item }}"
        dest: /usr/sbin/{{ item }}
        owner: root
        group: root
        mode: "755"
        remote_src: yes
      loop:
        - kubectl
        - oc
        - oc-mirror
    - name: Check if directory {{ user_home.stdout }}/.docker exists
      tags: mirror_artifacts
      ansible.builtin.stat:
        path: "{{ user_home.stdout }}/.docker"
      register: home_docker
    - name: Create directory {{ user_home.stdout }}/.docker
      tags: mirror_artifacts
      file:
        path: "{{ user_home.stdout }}/.docker"
        state: directory
      when: not home_docker.stat.exists
    - name: create pull secret file for mirroring
      tags: mirror_artifacts
      ansible.builtin.template:
        src: mirror-secret.json.j2
        dest: "{{ user_home.stdout }}/.docker/config.json"
        backup: yes
        force: yes
    - name: create ca cert file for adding to ca trust when ca is not trusted and updating ca trust
      tags: mirror_artifacts
      become: true
      block:
        - name: create ca cert file when ca is untrusted
          ansible.builtin.template:
            src: ca.crt.j2
            dest: /etc/pki/ca-trust/source/anchors/registry.crt
            force: yes
        - name: update ca trust with the cert file
          ansible.builtin.shell: |
            set -o pipefail
            update-ca-trust
      when: not disconnected.registry.ca_trusted
    - name: mirror the platform the legacy way if legacy mode is enabled
      tags: mirror_artifacts
      block:
        - name: run the oc adm release mirror command
          ansible.builtin.shell: |
            set -o pipefail
            oc adm -a {{ user_home.stdout }}/.docker/config.json release mirror \
             --from=quay.io/openshift-release-dev/ocp-release:{{ disconnected.mirroring.legacy.ocp_quay_release_image_tag }} \
             --to={{ disconnected.registry.url }}/{{ disconnected.mirroring.legacy.ocp_org }}/{{ disconnected.mirroring.legacy.ocp_repo }} \
             --to-release-image={{ disconnected.registry.url }}/{{ disconnected.mirroring.legacy.ocp_org }}/{{ disconnected.mirroring.legacy.ocp_repo }}:{{ disconnected.mirroring.legacy.ocp_tag }}
          register: cmd_oc_legacy_mirroring
        - name: print the output of the mirroring
          ansible.builtin.debug:
            var: cmd_oc_legacy_mirroring.stdout_lines
      when: disconnected.mirroring.legacy.platform
    - name: prepare imageset for oc-mirror mirroring
      tags: mirror_artifacts
      ansible.builtin.template:
        src: imageset.yaml.j2
        dest: "{{ user_home.stdout }}/ocpinst_disconnected/imageset.yaml"
    - name: mirror the imageset to registry
      tags: mirror_artifacts
      block:
        - name: mirror the imageset to registry for oc-mirror plugin v1
          ansible.builtin.shell: |
            set -o pipefail
            oc mirror --config {{ user_home.stdout }}/ocpinst_disconnected/imageset.yaml docker://{{ disconnected.registry.url}} --ignore-history{{ ' --continue-on-error' if disconnected.mirroring.oc_mirror.oc_mirror_args.continue_on_error == True }} \
             {{ ' --source-skip-tls' if disconnected.mirroring.oc_mirror.oc_mirror_args.source_skip_tls == True }}
          # ignore-history set by default for idempotency
          register: cmd_oc_mirror
          args:
            chdir: "{{ user_home.stdout }}/ocpinst_disconnected"
          when: disconnected.mirroring.oc_mirror.image_set.apiVersion == "mirror.openshift.io/v1alpha2"
        - name: dry run the imageset for creating mapping.txt file for oc-mirror plugin v2
          ansible.builtin.shell: |
            set -o pipefail
            oc mirror --v2 --config {{ user_home.stdout }}/ocpinst_disconnected/imageset.yaml --workspace file://{{ user_home.stdout }}/ocpinst_disconnected docker://{{ disconnected.registry.url}} --dry-run
          args:
            chdir: "{{ user_home.stdout }}/ocpinst_disconnected"
          when: disconnected.mirroring.oc_mirror.image_set.apiVersion == "mirror.openshift.io/v2alpha1"
        - name: mirror the imageset to registry for oc-mirror plugin v2
          ansible.builtin.shell: |
            set -o pipefail
            oc mirror --v2 --config {{ user_home.stdout }}/ocpinst_disconnected/imageset.yaml --workspace file://{{ user_home.stdout }}/ocpinst_disconnected docker://{{ disconnected.registry.url}}
          register: cmd_oc_mirror
          args:
            chdir: "{{ user_home.stdout }}/ocpinst_disconnected"
          when: disconnected.mirroring.oc_mirror.image_set.apiVersion == "mirror.openshift.io/v2alpha1"
        - name: print output of imageset mirroring
          ansible.builtin.debug:
            var: cmd_oc_mirror
    - name: Get the results directory from oc mirror v1 plugin operation
      tags: mirror_artifacts
      ansible.builtin.shell: |
        set -o pipefail
        ls {{ user_home.stdout }}/ocpinst_disconnected/oc-mirror-workspace/ | grep results
      register: oc_mirror_results_dir_name
      when: disconnected.mirroring.oc_mirror.image_set.apiVersion == "mirror.openshift.io/v1alpha2"
    - name: perform post mirror actions if requested
      tags: mirror_artifacts
      block:
        - name: post mirroring operation for oc mirror v1 plugin
          block:
            - name: create a copy of the mappings file
              ansible.builtin.copy:
                src: "{{ user_home.stdout }}/ocpinst_disconnected/oc-mirror-workspace/{{ oc_mirror_results_dir_name.stdout }}/mapping.txt"
                dest: "{{ user_home.stdout }}/ocpinst_disconnected/oc-mirror-workspace/{{ oc_mirror_results_dir_name.stdout }}/post_mapping.txt"
                mode: preserve
                remote_src: True
            - name: replace provided values in the mappings
              ansible.builtin.replace:
                path: "{{ user_home.stdout }}/ocpinst_disconnected/oc-mirror-workspace/{{ oc_mirror_results_dir_name.stdout }}/post_mapping.txt"
                regexp: "{{ item.regexp }}"
                replace: "{{ item.replace }}"
              with_items: "{{ disconnected.mirroring.oc_mirror.post_mirror.mapping.replace.list }}"
              when:  disconnected.mirroring.oc_mirror.post_mirror.mapping.replace.enabled
            - name: manually mirror patched mappings to registry
              ansible.builtin.shell: |
                set -o pipefail
                oc image mirror -a {{ user_home.stdout }}/.docker/config.json -f {{ user_home.stdout }}/ocpinst_disconnected/oc-mirror-workspace/{{ oc_mirror_results_dir_name.stdout }}/post_mapping.txt --insecure --filter-by-os='.*' --continue-on-error || true
              args:
                chdir: "{{ user_home.stdout }}/ocpinst_disconnected"
              register: cmd_oc_image_mirror
            - name: print output of oc image mirror
              ansible.builtin.debug:
                var: cmd_oc_image_mirror
          when: disconnected.mirroring.oc_mirror.image_set.apiVersion == "mirror.openshift.io/v1alpha2"
        - name: post mirroring operation for oc mirror v2 plugin
          block:
            - name: Check if directory {{ user_home.stdout }}/.config exists
              tags: mirror_artifacts
              ansible.builtin.stat:
                path: "{{ user_home.stdout }}/.config"
              register: container_registry_home
            - name: Create directory {{ user_home.stdout }}/.config/containers
              tags: mirror_artifacts
              file:
                path: "{{ user_home.stdout }}/.config/containers"
                state: directory
              when: not container_registry_home.stat.exists
            - name: prepare registries.conf for oc-mirror mirroring
              tags: mirror_artifacts
              ansible.builtin.template:
                src: registries.conf.j2
                dest: "{{ user_home.stdout }}/.config/containers/registries.conf"
            - name: mirror the imageset to registry for oc-mirror plugin v2
              ansible.builtin.shell: |
                set -o pipefail
                oc mirror --v2 --config {{ user_home.stdout }}/ocpinst_disconnected/imageset.yaml --workspace file://{{ user_home.stdout }}/ocpinst_disconnected docker://{{ disconnected.registry.url}}
              register: cmd_oc_image_mirror
              args:
                chdir: "{{ user_home.stdout }}/ocpinst_disconnected"
            - name: print output of oc image mirror
              ansible.builtin.debug:
                var: cmd_oc_image_mirror
          when: disconnected.mirroring.oc_mirror.image_set.apiVersion == "mirror.openshift.io/v2alpha1"
      when:  disconnected.mirroring.oc_mirror.post_mirror.mapping.replace.enabled
    - name: Fetch the files that need to be applied on the cluster to the controller for oc-mirror v1 plugin
      tags: mirror_artifacts
      ansible.posix.synchronize:
        mode: pull
        src: "{{ user_home.stdout }}/ocpinst_disconnected/oc-mirror-workspace/{{ oc_mirror_results_dir_name.stdout }}/*"
        dest: "../.oc-mirror-results"
      when: disconnected.mirroring.oc_mirror.image_set.apiVersion == "mirror.openshift.io/v1alpha2"
    - name: Fetch the files that need to be applied on the cluster to the controller for oc-mirror v2 plugin
      tags: mirror_artifacts
      ansible.posix.synchronize:
        mode: pull
        src: "{{ user_home.stdout }}/ocpinst_disconnected/working-dir/cluster-resources/*"
        dest: "../.oc-mirror-results"
      when: disconnected.mirroring.oc_mirror.image_set.apiVersion == "mirror.openshift.io/v2alpha1"
  when: disconnected.enabled
