---

- hosts: hypervisors
  tags: create_bastion
  gather_facts: false
  tasks:
    - name: Determine which hypervisor is hosting the bastion.
      set_fact:
        hypervisor_with_bastion: "{{ inventory_hostname }}"
      when: "'bastion' in guests and hostvars['bastion'].create"

- hosts: "{{ hypervisor_with_bastion | default('hypervisor_1') }}"
  gather_facts: true
  roles:
    - common
  post_tasks:
    - name: Create bastion.
      include_role: 
        name: create_bastion
      when: hostvars['bastion'].create
