# Assume we have an existing ftp/http server already
- name: 4 create bastion
  hosts: kvm_host[0]
  become: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
    - "{{ inventory_dir }}/group_vars/secrets.yaml"
    - "{{ inventory_dir }}/host_vars/{{ env.z.lpar1.hostname }}.yaml"
  roles:
    - common
    - { role: create_bastion, when: env.bastion.create == True }

- name: 4 create bastion - copy SSH key from localhost to access bastion
  hosts: localhost
  tags: ssh, ssh_copy_id
  gather_facts: true
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
    - "{{ inventory_dir }}/group_vars/secrets.yaml"
  vars:
    ssh_target: ["{{ env.bastion.networking.ip }}", "{{ env.bastion.access.user }}", "{{ env.bastion.access.pass }}", "{{ path_to_key_pair }}"]
  roles:
    - { role: ssh_copy_id, when: env.bastion.create == True }
