- name: Create Agents
  hosts: kvm_host_hypershift
  become: true
  roles:
  - boot_agents_hypershift

- name: Boot zvm nodes
  hosts: bastion_hypershift
  tasks:
    - name:  Install tessia baselib
      import_role:
        name: install_tessia_baselib
      when: hypershift.compute_node_type | lower == 'zvm'

    - name: Start zvm nodes
      include_tasks: ../roles/boot_zvm_nodes_hypershift/tasks/main.yaml
      loop: "{{ range(hypershift.agents_parms.agents_count | int) | list }}"
      when: hypershift.compute_node_type | lower == 'zvm'

- name: Scale Nodepool & Configure Haproxy on bastion for hosted workers
  hosts: bastion_hypershift
  roles:
  - scale_nodepool_and_wait_for_compute_hypershift
  - add_hc_workers_to_haproxy_hypershift

- name: Wait for all Console operators to come up
  hosts: bastion_hypershift
  roles:
  - wait_for_hc_to_complete_hypershift
