- name: Download Required images for booting Agents
  hosts: "{{ 'kvm_host_hcp' if 'kvm_host_hcp' in groups['all'] else 'bastion_hcp' }}"
  become: true
  roles:
  - setup_for_agents_hcp

- name: Configure httpd on bastion for hosting rootfs
  hosts: bastion_hcp
  tasks:
    - name: Download rootfs image
      include_role:
        name: download_rootfs_hcp
      when: ( hcp.data_plane.kvm.boot_method | lower != 'iso' and hcp.compute_node_type | lower == 'kvm' ) or hcp.compute_node_type | lower != 'kvm'

- name: Create Agents
  hosts: kvm_host_hcp
  become: true
  roles:
    - boot_agents_hcp

- name: Boot zvm nodes
  hosts: bastion_hcp
  tasks:
    - name: Getting packages for zvm
      ansible.builtin.set_fact.set_fact:
        env:
          pkgs:
            zvm: "{{ hcp.pkgs.zvm }}"
      when: hcp.compute_node_type | lower == 'zvm'

    - name: Install tessia baselib
      ansible.builtin.import_role:
        name: install_tessia_baselib
      when: hcp.compute_node_type | lower == 'zvm'

    - name: Start zvm nodes
      include_tasks: ../roles/boot_zvm_nodes_hcp/tasks/main.yaml
      loop: "{{ range(hcp.data_plane.compute_count | int) | list }}"
      when: hcp.compute_node_type | lower == 'zvm'

- name: Boot LPARs
  hosts: bastion_hcp
  vars_files:
    - "{{playbook_dir}}/secrets.yaml"
  tasks:

    - name: Install tessia baselib
      ansible.builtin.import_role:
        name: install_tessia_baselib
      when: hcp.compute_node_type | lower == 'lpar'

    - name: Boot LPARs
      ansible.builtin.include_tasks: ../roles/boot_LPAR_hcp/tasks/main.yaml
      loop: "{{ range(hcp.data_plane.compute_count | int) | list }}"
      when: hcp.compute_node_type | lower == 'lpar'


- name: Scale Nodepool & Configure Haproxy on bastion for hosted workers
  hosts: bastion_hcp
  roles:
    - scale_nodepool_and_wait_for_compute_hcp
    - add_hc_workers_to_haproxy_hcp

- name: Wait for all Console operators to come up
  hosts: bastion_hcp
  roles:
  - wait_for_hc_to_complete_hcp
