---
- name: Install Prerequisites on kvm_host
  hosts: kvm_host_hcp
  become: true
  vars_files:
    - "{{playbook_dir}}/secrets.yaml"
  tasks:
    - name: Setting host
      set_fact:
        host: 'kvm_host_hcp'
      when: hcp.compute_node_type | lower != 'zvm'

    - name: Install Prereqs on host
      import_role:
        name:  install_prerequisites_host_hcp
      when: hcp.compute_node_type | lower != 'zvm'
     
    - name: Setting vars for storage pool configuration
      set_fact:
        env:
          cluster:
            networking:
              metadata_name: "{{ hcp.control_plane.hosted_cluster_name }}"
        storage:
          pool_path: "{{ hcp.data_plane.kvm.storage.qcow.pool_path }}"
      when: hcp.data_plane.kvm.storage.type | lower  != 'dasd' and hcp.compute_node_type | lower == 'kvm'

    - name: Configure Storage pool
      import_role:
        name: configure_storage
      when: hcp.data_plane.kvm.storage.type | lower  != 'dasd' and hcp.compute_node_type | lower == 'kvm'

- name: Create macvtap network
  hosts: kvm_host_hcp
  become: true
  tasks:
    - name: Getting interface name
      shell: ip -o -f inet addr show | grep "{{ hcp.bastion_params.host}}" | awk '{print $2}' | tr -d ':'
      register: network_interface

    - name: Setting interface name
      set_fact:
        networking:
          device1: "{{ network_interface.stdout }}"
        env:
          vnet_name: macvtap
      when: hcp.compute_node_type | lower != 'zvm'

    - name:  Creating macvtap network
      import_role:
        name: macvtap
      when: hcp.compute_node_type | lower != 'zvm'

- name: Create bastion for hcp
  hosts: kvm_host_hcp
  become: true
  vars_files:
    - "{{playbook_dir}}/secrets.yaml"
  tasks:
    - name: Creating Bastion
      include_role:
        name: create_bastion_hcp
      when: 
        - hcp.bastion_params.create == true
        - hcp.compute_node_type | lower != 'zvm'

- name: Configuring Bastion
  hosts: bastion_hcp
  become: true
  vars_files:
    - "{{playbook_dir}}/secrets.yaml"
  tasks:
    - name: Setting host
      set_fact:
        host: 'bastion_hcp'
        env:
          ansible_key_name: "{{ hcp.ansible_key_name }}"  
        
    - name: Install Prereqs
      import_role:
        name: install_prerequisites_host_hcp
        
    - name: Configure Bastion
      import_role:
        name: install_prereqs_bastion_hcp

    - name: Add ansible SSH key to ssh-agent
      import_role:
        name: ssh_agent
    
- name: Create AgentServiceConfig Hosted Control Plane and InfraEnv
  hosts: bastion_hcp
  vars_files:
    - "{{playbook_dir}}/secrets.yaml"
  roles:
  - install_mce_operator
  - create_agentserviceconfig_hcp
  - create_hcp_InfraEnv

- name: Download Required images for booting Agents
  hosts: "{{ 'kvm_host_hcp' if 'kvm_host_hcp' in groups['all'] else 'bastion_hcp' }}"
  become: true
  roles:
  - setup_for_agents_hcp

- name: Configure httpd on bastion for hosting rootfs
  hosts: bastion_hcp
  tasks:
    - name: Download rootfs image
      include_role:
        name: download_rootfs_hcp
      when: ( hcp.data_plane.kvm.boot_method | lower != 'iso' and hcp.compute_node_type | lower == 'kvm' ) or hcp.compute_node_type | lower != 'kvm'
