---

- name: Install Prerequisites on kvm_host
  hosts: kvm_host_hypershift
  vars_files:
    - "{{playbook_dir}}/secrets.yaml"

  roles:
  - install_prerequisites_host_hypershift



- name: Create AgentServiceConfig Hosted Control Plane and InfraEnv
  hosts: kvm_host_hypershift
  vars_files:
    - "{{playbook_dir}}/secrets.yaml"
  roles:
  - create_agentserviceconfig_hypershift
  - create_hcp_InfraEnv_hypershift

