---
- hosts: localhost
  tags: localhost
  connection: local
  become: false
  gather_facts: true
  vars_files:
    - "{{ inventory_dir }}/group_vars/disconnected.yaml"
    - "{{ inventory_dir }}/group_vars/zvm.yaml"
  roles:
    - set_inventory

- name: Destroy ABI Cluster
  hosts: kvm_host[0]
  become: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
  roles:
    - delete_nodes
    - destroy_bastion
    - cleanup_kvm
