---
- name: Download kubeconfig and kubepassw files from bastion host
  hosts: bastion
  gather_facts: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
    - "{{ inventory_dir }}/group_vars/secrets.yaml"
  roles:
    - download_kubeconfig

# Assisted by Bob
