---
# Import Playbook To Generate Inventory & Adding SSH-Keys
- import_playbook: 0_setup.yaml

# Import Playbook To Install Prerequisites On KVM_HOST
- import_plyabook: 3_setup_kvm_host.yaml

# Create Bastion 
- name: Create Bastion
  hosts: kvm_host[0]
  become: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
  roles:
    - common
    - { role: create_bastion, when: env.bastion.create == True }

# Set Up DNS On Bastion
- name: Set Up DNS On Bastion
  hosts: bastion
  become: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
  roles:
    - { role: dns, when: env.bastion.options.dns }

# Set Up HAProxy On Bastion
- name: Set Up HAProxy On Bastion
  hosts: bastion
  become: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
  roles:
    - common
    - role: sno_haproxy

# Prepare AgentConfig & InstallConfig

# Build initrd.img, rootfs.img & kernelfs.img 

# Boot The VM using initrd.img, rootfs.img & kernelfs.img 

# !!!!!!!!!!!!!!!!! YAY SNO IS UP !!!!!!!!!!!!!!!!! #