---

# Import Playbook To Generate Inventory & Adding SSH-Keys
- import_playbook: 0_setup.yaml

# Import Playbook To Install Prerequisites On KVM_HOST
- import_plyabook: 3_setup_kvm_host.yaml

# Import Playbook To Create Bastion
- import_plyabook: 4_create_bastion

# Import Playbook To Configure
- import_playbook: 5_setup_bastion

# Create Bastion 
- name: Create Bastion
  hosts: kvm_host[0]
  become: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
  roles:
    - common
    - { role: create_bastion, when: env.bastion.create == True }


# Set Up DNS On Bastion
- name: Set Up DNS On Bastion
  hosts: bastion
  become: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
  roles:
    - { role: dns, when: env.bastion.options.dns }

# Set Up HAProxy On Bastion
- name: Set Up HAProxy On Bastion
  hosts: bastion
  become: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
  roles:
    - common
    - role: sno_haproxy

# Download Openshift Installer
- name: Download Openshift Installer
  hosts: bastion
  become: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
  roles:
    - role: download_ocp_installer

# Prepare AgentConfig & InstallConfig
- name: Prepare AgentConfig & InstallConfig
  hosts: bastion
  become: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
  roles:
    - role: prepare_configs

# Create Agents || Build initrd.img, rootfs.img & kernelfs.img 
- name: Build initrd.img, rootfs.img & kernelfs.img 
  hosts: bastion
  become: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
  roles:
    - role: create_agent
  
  # Boot ABI Agents 
- name: Boot ABI Agents
  hosts: kvm_host[0]
  become: false
  vars_files:
    - "{{ inventory_dir }}/group_vars/all.yaml"
  roles:
    - common
    - boot_abi_agents 

# Boot The VM using initrd.img, rootfs.img & kernelfs.img 

# !!!!!!!!!!!!!!!!! YAY SNO IS UP !!!!!!!!!!!!!!!!! #