# Master playbook For ABI . If you want to do everything all in one, use this.
---

- name: 0 - Setup inventory and SSH keys
  import_playbook: 0_setup.yaml
- name: 3 - Setup KVM host prerequisites
  import_playbook: 3_setup_kvm_host.yaml
- name: 4 - Create bastion
  import_playbook: 4_create_bastion.yaml
- name: 5 - Setup bastion
  import_playbook: 5_setup_bastion.yaml
- name: Mirror disconnected artifacts
  import_playbook: disconnected_mirror_artifacts.yaml
  when: disconnected.enabled
- name: Create ABI cluster
  import_playbook: create_abi_cluster.yaml
- name: Monitor ABI cluster installation
  import_playbook: monitor_create_abi_cluster.yaml
