---
# Setup inventory and passwordless SSH for bastion
- name: Setup inventory and passwordless SSH
  hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/../inventories/default/group_vars/secrets.yaml"
    - "{{ playbook_dir }}/../inventories/default/group_vars/hcp-kubevirt.yaml"
  roles:
    - create_inventory_setup_hcp_kubevirt
