# ocp_download_url with '/' at the end !
ocp_download_url: "https://mirror.openshift.com/pub/openshift-v4/multi/clients/ocp/latest/s390x/"
# ocp client and installer filenames
ocp_client_tgz: "openshift-client-linux.tar.gz"
ocp_install_tgz: "openshift-install-linux.tar.gz"

# rhcos_download_url with '/' at the end !
rhcos_download_url: "https://mirror.openshift.com/pub/openshift-v4/s390x/dependencies/rhcos/latest/"

# RHCOS live image filenames
rhcos_live_rootfs: "rhcos-live-rootfs.s390x.img"

# Openshift Settings
install_config_defaults:
  api_version: v1
  compute:
    architecture: s390x
    hyperthreading: Enabled
  control:
    architecture: s390x
    hyperthreading: Enabled
  cluster_network:
    cidr: 10.128.0.0/14
    host_prefix: 23
    type: OVNKubernetes
  service_network: 172.30.0.0/16
  machine_network: 192.168.122.0/24
  fips: false

# (Optional) Proxy
use_proxy: false
proxy_http:
proxy_https:
proxy_no:

# (Optional) CEX Ignition specific
# Default mappings based on cex_device
output_dir: "/tmp"
butane_default:
  version: 4.19.0
  dasd:
    layout: s390x-eckd
    device: /dev/dasd
  virt:
    layout: s390x-virt
    device: /dev/disk/by-partlabel/root
  fcp:
    layout: s390x-fcp  # or s390x-fcp if needed
    device: /dev/disk/by-label/root
