name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - 'mkdocs.yaml'
      - 'docs/**'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Fetch Latest gh-pages Branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git pull origin gh-pages
          git checkout main

      - name: Install mkdocs
        run: pip install mkdocs

      - name: Deploy docs
        run: python3 -m mkdocs gh-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
