---

- name: Create ssh config file (or add to an exsting file) to if network mode is NAT
  tags: ssh_copy_id, ssh
  ansible.builtin.blockinfile:
    path: ~/.ssh/config
    backup: true
    create: true
    block: |
      Host {{ hostvars['jumphost'].ansible_host }} 
        HostName {{ hostvars['jumphost'].ansible_host }}
        User {{ hostvars['jumphost'].ansible_user }}
        IdentityFile {{ hostvars['jumphost'].ansible_ssh_private_key_file }}
      Host {{ hostvars['bastion'].bastion_ip }}
        HostName {{ hostvars['bastion'].bastion_ip }} 
        User {{ hostvars['bastion'].bastion_user }}
        IdentityFile {{ hostvars['jumphost'].ansible_ssh_private_key_file }}
        ProxyJump {{ hostvars['jumphost'].ansible_host }} 
